### ISSUE TITLE
ecsstatic on Nextjs: SSR and streaming?

### ISSUE THREAD

**Issue by JuanPastenCastillo** [mayank99/ecsstatic#24]
Hi! Just a question: I really like this type of library and I would like to know if there's any plan to add the compatibility for Nextjs using Server Side Rendering and Streaming of data?

Thanks for all the hard work ♥

**Comment by mayank99** [comment]
Thanks for opening this issue and for the kind words. It's a good question. Unfortunately the answer is No.

Next.js opaquely uses Webpack, and I'm not too keen on writing a Webpack loader and potentially having to take additional steps to support Next.js features.

ecsstatic is intentionally designed for vite, and I kinda wish Next.js was also using vite. They are currently working on Turbopack, but it uses the same complicated API as Webpack. (Maybe if they ever expose a simpler plugin API, it could be an option.)

The good news is that there are already more popular solutions out there, such as pandaCSS and pigmentCSS. You might want to look into those instead of ecsstatic.

Hope that helps.

**Comment by JuanPastenCastillo** [comment]
Thank you very much for your answer @mayank99, I understand what you are saying.

The very good thing of «ecsstatic» is that the syntax is very similar to native CSS (styled components and emotions do it too) and there are very few CSS-in-JS options with that kind of syntax and with the possibility to use it in Nextjs with SSR or streaming. But I get the point. I hope that one day Nextjs will make the changes to build more tools on their platform easily because they talk a lot about the "developer experience".

So, thank you @mayank99 for your answer and I will use «ecsstatic» if I have to use plain React in the future ♥
